"""A fake LLMClient for local/dev runs — no network, no API cost.

Implements the same ``LLMClient`` protocol as the real backends, so it drops
into the generator and triage paths unchanged. It never calls a tool: it
returns a single ``end_turn`` response carrying canned Markdown, which lets the
generator loop terminate in one turn. Token counts are synthesised from the
content length so per-job logging and stored metadata look realistic.

Wire it in with ``--no-llm`` on the CLI or ``GREENBEAN_NO_LLM=1`` in the env.
"""

from __future__ import annotations

import re
from collections.abc import Sequence

from greenbean.core.llm import (
    LLMResponse,
    Message,
    TextBlock,
    ToolDefinition,
    Usage,
    UserMessage,
)

_DOC_RE = re.compile(r"`([^`]+)`")


def _target_doc(messages: Sequence[Message]) -> str:
    """Best-effort pull of the doc path from the first user message."""
    for msg in messages:
        if isinstance(msg, UserMessage) and isinstance(msg.content, str):
            match = _DOC_RE.search(msg.content)
            if match:
                return match.group(1)
    return "doc"


def _fake_markdown(doc: str, model: str) -> str:
    return (
        f"# {doc}\n\n"
        f"_Fake content generated by greenbean's no-LLM dev mode "
        f"(model placeholder: `{model}`)._\n\n"
        "This document was produced without calling any LLM API, so its prose "
        "is a placeholder. The surrounding pipeline — planning, diffing, "
        "publishing to the output dir, and state bookkeeping — ran for real.\n\n"
        f"<!-- src: {doc}:1-1 -->\n"
    )


class FakeClient:
    """LLMClient that returns deterministic canned responses, no network."""

    async def send_messages(
        self,
        *,
        model: str,
        system: str,
        messages: Sequence[Message],
        tools: Sequence[ToolDefinition],
        max_tokens: int,
    ) -> LLMResponse:
        doc = _target_doc(messages)
        content = _fake_markdown(doc, model)
        return LLMResponse(
            content=[TextBlock(text=content)],
            stop_reason="end_turn",
            # Rough but stable token estimate (~4 chars/token) so logs/metadata
            # downstream see non-zero, deterministic usage.
            usage=Usage(
                input_tokens=len(system) // 4,
                output_tokens=len(content) // 4,
            ),
        )
